language: generic

env:
  - PROJECT=projects/hello/
  - PROJECT=projects/world/
  - PROJECT=projects/he/

before_script: echo $TRAVIS_COMMIT_RANGE
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && npm run test; fi
