language: generic

matrix:
  include:
  - env: PROJECT=projects/hello/
    node_js: lts
  - env: PROJECT=projects/world/
    node_js: 7
  - env: PROJECT=projects/he/

before_script: echo $TRAVIS_COMMIT_RANGE
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && npm run test; else echo "NO CHANGES SINCE LAST COMMIT"; fi
